name: Build WebGL and Push to Docs Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build Unity project
        uses: game-ci/unity-builder@v2.0.0
        with:
          targetPlatform: WebGL
          unityVersion: 2021.1.17f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Push to Docs Branch
        uses: ad-m/github-push-action@master
        with:
          branch: docs
          directory: ./build
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}